version: '3'

services:
    nginx_proxy:
      image: nginx 
      container_name: nginx_proxy 
      ports:
        - "80:80"  # <host port>:<container port>
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - my-dotnet-app 

    my-dotnet-app:
       container_name: my-dotnet-app
       build: . 
       ports:
          - "8090:8080"  # <host port>:<container port>
       depends_on:
         - ms-sql-server

    ms-sql-server:
       image: mcr.microsoft.com/azure-sql-edge
       container_name: ms-sql-server
       environment:
         - ACCEPT_EULA="Y" 
         - SA_PASSWORD=ronit@1992
       restart: always
       ports: 
         - 1433:1433  # <host port>:<container port>
#       volumes:
#         - sqlserver-data:/var/opt/mssql   # Persist data

    adminer: 
      image: adminer 
      container_name: adminer
      restart: always 
      ports: 
        - 8080:8080  # <host port>:<container port>
